### ISSUE TITLE
How to train on the NeRF synthetic dataset

### ISSUE THREAD

**Issue by zhutengjie** [FuxiComputerVision/Nefii#1]
Thanks for your great work! I want to train your work using  the NeRF synthetic dataset, but I don't know how to convert the NeRF synthetic dataset to the form like the thin_cube, could you tell me how to do it, thanks!

**Comment by Woolseyyy** [comment]
Hi! Thanks for your kind words. Regarding your query, I'm not familiar with the term "thin_cube." Could you provide more details or clarify what you mean by "thin_cube"? This will help me understand your needs better and assist you more effectively. Thanks!

**Comment by zhutengjie** [comment]
Thanks for your reply. I have found the code to convert the dataset successfully.
